[package]
name = "smash-core"
version.workspace = true
edition.workspace = true

[dependencies]
ropey = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
tempfile = "3"
