[package]
name = "smash-terminal"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror = { workspace = true }
tracing = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
smash-input = { path = "../smash-input" }

[dev-dependencies]
